// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration — uses the same API key as Android.
  // For production, register a Web app in Firebase Console and replace the appId.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsmahZ-zyp9QuNbBo2CAjOQiDCKMJnHs',
    appId: '1:581813390000:web:000000000000000000000000',
    messagingSenderId: '581813390000',
    projectId: 'namur-5095e',
    authDomain: 'namur-5095e.firebaseapp.com',
    storageBucket: 'namur-5095e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsmahZ-zyp9QuNbBo2CAjOQiDCKMJnHs',
    appId: '1:581813390000:android:be2f9158368c7521ae8975',
    messagingSenderId: '581813390000',
    projectId: 'namur-5095e',
    storageBucket: 'namur-5095e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvsmahZ-zyp9QuNbBo2CAjOQiDCKMJnHs',
    appId: '1:581813390000:ios:000000000000000000000000',
    messagingSenderId: '581813390000',
    projectId: 'namur-5095e',
    storageBucket: 'namur-5095e.appspot.com',
    iosClientId: '581813390000-71tugo5f6j3uk6grgc6.apps.googleusercontent.com',
    iosBundleId: 'com.activeitzone.namur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvsmahZ-zyp9QuNbBo2CAjOQiDCKMJnHs',
    appId: '1:581813390000:ios:000000000000000000000000',
    messagingSenderId: '581813390000',
    projectId: 'namur-5095e',
    storageBucket: 'namur-5095e.appspot.com',
    iosClientId: '581813390000-71tugo5f6j3uk6grgc6.apps.googleusercontent.com',
    iosBundleId: 'com.activeitzone.namur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvsmahZ-zyp9QuNbBo2CAjOQiDCKMJnHs',
    appId: '1:581813390000:web:000000000000000000000000',
    messagingSenderId: '581813390000',
    projectId: 'namur-5095e',
    authDomain: 'namur-5095e.firebaseapp.com',
    storageBucket: 'namur-5095e.appspot.com',
  );
}
